name: Ci Workflow

on:
  push:
    branches:
      -master
jobs:
  build:
    runs -on: ubantu-latest

  steps:
    -name: checkout code
    user: action/checkout@v4

    -name:Run CI-Demo
    run: echo "Build and Test Successful"